package com.airplayer.service

/**
 * AirPlayerService stub for JVM test compilation.
 *
 * The real AirPlayerService extends android.app.Service and depends on
 * NotificationCompat (AndroidX) and the R resource class (generated by AGP),
 * neither of which are available in the standalone JVM test runner.
 *
 * This stub provides only the companion object constants that are needed by
 * ServiceController (at compile time) and ServiceControllerTest / AirPlayerServiceTest
 * (at test time). No Android lifecycle methods are present.
 */
class AirPlayerService {
    companion object {
        const val ACTION_START   = "com.airplayer.action.START"
        const val ACTION_STOP    = "com.airplayer.action.STOP"
        const val ACTION_RESTART = "com.airplayer.action.RESTART"
        const val NOTIFICATION_ID = 1
        const val CHANNEL_ID     = "airplayer_service"
    }
}
